### ISSUE TITLE
If validation in step is successful, then i can skip the rest steps.

### ISSUE THREAD

**Issue by fromnt34** [tushargugnani/vue-step-wizard#11]
I noticed that when valid data is entered at one step, then after I can move through other steps How can i fix it?
Thanks.

**Comment by tushargugnani** [comment]
If I understand the question correctly, for some of the steps you want to validation? For that you can just simply provide blank object in the validation array. Something like this

```
validationRules:[
        {fullName: {required}, email: {required, email} },  //Validation Rules for step 1
        {},   //No Validation for step 2
        {referral: {required}, terms: {required, numeric} }   //Validation for step 3
    ]
```

**Comment by fromnt34** [comment]
No. Sorry for my english. For example I have 3 steps:
```
validationRules: [
        {
           name: { required, minLength: minLength(2) },
           surname: { required, minLength: minLength(2) }
        {
           petName: { required, minLength: minLength(2) },
           petSurname: { required, minLength: minLength(2) }
        },
        {
           country: { required },
           street: { required }
        }
]
```
All steps are validated. My actions:
- I'm at the first step.
- Enter a valid name and last surname.
- supposed to, I should go to the second step, but I notice that I can also go straight to the third step by skipping the second one.

It turns out that by entering valid data at a step, you can skip the rest steps. But I don't need the user to be able to skip the steps. How can this be fixed?

**Comment by tushargugnani** [comment]
Let me look into this.

**Comment by tushargugnani** [comment]
@fromnt34 Can you please update to the latest version and check again?

**Comment by fromnt34** [comment]
@tushargugnani sorry for not answering your penultimate question. Yes, in version 0.1.16 everything works perfect. Thanks.
