### ISSUE TITLE
Cannot read property '_c' of undefined     at Proxy.render (vue-step-wizard.common.js:2036)

### ISSUE THREAD

**Issue by gstamosbg** [tushargugnani/vue-step-wizard#17]
Is there support for vuejs 3 or?

![image](https://user-images.githubusercontent.com/6755277/110493635-7996ba80-80fb-11eb-8163-1d0893d053e5.png)

**Comment by DrMarkEy** [comment]
I got the same issue with vuejs 3...

**Comment by tushargugnani** [comment]
I haven't tested this package with Vue 3 , Will be making adjustments to make it work with Vue 3 as well. Thanks for reporting the issue.

**Comment by DejiAwoniyi** [comment]
Hi @tushargugnani any update on this?

**Comment by tushargugnani** [comment]
Sorry, this plugin does not support Vue 3
