### ISSUE TITLE
Note More then 3 tabs

### ISSUE THREAD

**Issue by maliprem** [tushargugnani/vue-step-wizard#18]
Unable to create tabs more then 3. If I try to create it shows up but does not move to next step. Doesn't it work with 3 steps only ?

**Comment by tushargugnani** [comment]
@maliprem it should work with any number of tabs. Will look into this by testing more number of tabs.

**Comment by maliprem** [comment]
No! it's not working properly. I tried it many times.

**Comment by SlyDave** [comment]
You might need to provide some more details @maliprem , it's working fine with 4+ tabs on a basic demo version:

![image](https://user-images.githubusercontent.com/1842611/111498995-665a9f00-873a-11eb-9183-d37fdcfd1765.png)

**Comment by maliprem** [comment]
Just Try This https://codesandbox.io/s/vue-step-wizard-form-with-validation-forked-6v9n0?file=/src/components/StepFormValidation.vue  
![Untitled](https://user-images.githubusercontent.com/63595606/111595238-edb71980-87f1-11eb-8ecb-5bdbdd59277a.png)


It works only when there is no data no validation in between tabs.

**Comment by tushargugnani** [comment]
@maliprem I tested it with more than 3 tabs and it works fine. Make sure the validation array for the step is an empty array if you don't have any validations for the step 2 as you have in the above shown image.

**Comment by maliprem** [comment]
@tushargugnani  thanks for package and quick reply but still this is not working. 
Here my code.

<template>
  <form-wizard @onComplete="onComplete">
    <tab-content title="About You" :selected="true">
      <div class="form-group">
        <label for="fullName">Full Name</label>
        <input
          type="text"
          class="form-control"
          :class="hasError('fullName') ? 'is-invalid' : ''"
          placeholder="Enter your name"
          v-model="formData.fullName"
        >
        <div v-if="hasError('fullName')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.fullName.required">Please provide a valid name.</div>
        </div>
      </div>
      <div class="form-group">
        <label for="email">Your Email</label>
        <input
          type="email"
          class="form-control"
          :class="hasError('email') ? 'is-invalid' : ''"
          placeholder="Enter your email"
          v-model="formData.email"
        >
        <div v-if="hasError('email')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.email.required">Email field is required</div>
          <div class="error" v-if="!$v.formData.email.email">Should be in email format</div>
        </div>
      </div>
    </tab-content>
    <tab-content title="mytable"></tab-content>
    <tab-content title="About your Company">
      <div class="form-group">
        <label for="companyName">Your Company Name</label>
        <input
          type="text"
          class="form-control"
          :class="hasError('companyName') ? 'is-invalid' : ''"
          placeholder="Enter your Company / Organization name"
          v-model="formData.companyName"
        >
        <div v-if="hasError('companyName')" class="invalid-feedback">
          <div
            class="error"
            v-if="!$v.formData.companyName.required"
          >Please provide a valid company name.</div>
        </div>
      </div>
      <div class="form-group">
        <label for="numberOfEmployees">Number of Employees</label>
        <input
          type="text"
          class="form-control"
          :class="hasError('numberOfEmployees') ? 'is-invalid' : ''"
          placeholder="Enter Total Number of Employees"
          v-model="formData.numberOfEmployees"
        >
        <div v-if="hasError('numberOfEmployees')" class="invalid-feedback">
          <div
            class="error"
            v-if="!$v.formData.numberOfEmployees.required"
          >Please provide number of employees in your company.</div>
          <div class="error" v-if="!$v.formData.numberOfEmployees.numeric">Should be a valid value.</div>
        </div>
      </div>
    </tab-content>
    <tab-content title="Finishing Up">
      <div class="form-group">
        <label for="referral">From Where did you hear about us</label>
        <select
          :class="hasError('referral') ? 'is-invalid' : ''"
          class="form-control"
          v-model="formData.referral"
        >
          <option>Newspaper</option>
          <option>Online Ad</option>
          <option>Friend</option>
          <option>Other</option>
        </select>
        <div v-if="hasError('referral')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.referral.required">Please select on of the fields.</div>
        </div>
      </div>
      <div class="form-group form-check">
        <input
          type="checkbox"
          :class="hasError('terms') ? 'is-invalid' : ''"
          class="form-check-input"
          v-model="formData.terms"
        >
        <label class="form-check-label">I accpet terms & conditions</label>
        <div v-if="hasError('terms')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.terms.required">Please select terms and conditions.</div>
        </div>
      </div>
    </tab-content>
  </form-wizard>
</template>

<script>
import { FormWizard, TabContent, ValidationHelper } from "vue-step-wizard";
import "vue-step-wizard/dist/vue-step-wizard.css";
import { required } from "vuelidate/lib/validators";
import { email } from "vuelidate/lib/validators";
import { numeric } from "vuelidate/lib/validators";

export default {
  name: "StepFormValidation",
  components: {
    FormWizard,
    TabContent
  },
  mixins: [ValidationHelper],
  data() {
    return {
      formData: {
        fullName: "",
        email: null,
        companyName: null,
        numberOfEmployees: null,
        referral: null,
        terms: false
      },
      validationRules: [
        { fullName: { required }, email: { required, email } },
        { companyName: { required }, numberOfEmployees: { required, numeric } },
        { referral: { required }, terms: { required } }
      ]
    };
  },
  methods: {
    onComplete() {
      alert("Submitting Form ! Rock On");
    }
  }
};
</script>

**Comment by tushargugnani** [comment]
@maliprem Can you try pasting your code in pastebin ?

**Comment by maliprem** [comment]
<template>
  <form-wizard @onComplete="validateAndCreate" class="card-header">

    <tab-content title="Sanstha Basic Info" :selected="true">
      <div class="form-group ">
        <label for="name">Sanstha Name</label>
        <input
          type="text"
          class="form-control"
          :class="hasError('name') ? 'is-invalid' : ''"
          placeholder="Enter your Sanastha Name"
          v-model="formData.name"
        />
        <div v-if="hasError('name')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.name.required">
            Please provide a valid name.
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="caste">Select Caste <span class="star">*</span></label>
        <caste-select @casteSelected="setCaste"  :class="hasError('caste') ? 'is-invalid' : ''" ></caste-select>

         <div v-if="hasError('caste')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.caste.required">
            Select Caste
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="registered">Sanstha Registered</label>
        <select
          type="text"
          v-model="formData.registered"
          id="registered"
          name="registered"
          class="form-control"
          placeholder="Enter your Sanastha No."
        >
          <option>Yes</option>
          <option>No</option>
        </select>
      </div>
      <div class="form-group" v-if="formData.registered === 'Yes'">
        <label for="reg_no">Registration Number</label>
        <input
          type="text"
          class="form-control"
          placeholder="Enter your Sanastha Reg No."
          v-model="formData.reg_no"
        />
      </div>
    
    </tab-content>
    <tab-content title="About your Sanstha">
      <div class="form-group">
        <label for="subdomain">Sanstha Website Domain</label>
        <input
          type="text"
          class="form-control"
          :class="hasError('subdomain') ? 'is-invalid' : ''"
          placeholder="Enter Unique Domain without spaces"
          v-model="formData.subdomain"
        />
        <div v-if="hasError('subdomain')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.subdomain.required">
            Please provide a valid domain name.(Without any space and special
            eg.abcsanstha character)
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="redirecturl">Old Website Domain</label>
        <input
          type="text"
          class="form-control"
          placeholder="Enter Website domain if already have"
          v-model="formData.redirecturl"
        />
      </div>
      
    </tab-content>

    <tab-content title="Finishing Up">
      <div class="form-group">
        <label for="referral"> <b>Select Website Features</b></label>

        <ul>
          <li v-bind:key="data.name" v-for="data in featureList">
            <input
              type="checkbox"
              :value="data.name"
              id="data.name"
              v-model="formData.feature_name"
            />
            <span> {{ data.name.toUpperCase() }}</span>
          </li>
        </ul>
        <span>{{ formData.feature_name }}</span>
      </div>
      <br />
      <div class="form-group">
        <label for="template_id">Select Website Template</label>

        <div class="cc-selector">
          <br />
          <b-form-group
            label=""
            :class="hasError('template_id') ? 'is-invalid' : ''"
          >
            <div class="cc-selector">
              <input
                id="visa"
                type="radio"
                name="credit-card"
                value="template_001"
                v-model="formData.template_id"
              />
              <label class="drinkcard-cc visa" for="visa"></label>
              <input
                id="mastercard"
                type="radio"
                name="credit-card"
                value="template_002"
                v-model="formData.template_id"
              />
              <label class="drinkcard-cc mastercard" for="mastercard"></label>
            </div>
          </b-form-group>
        </div>
        <span>Picked: {{ formData.template_id }}</span>
        <div v-if="hasError('template_id')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.template_id.required">
            Please select a Template
          </div>
        </div>
      </div>
      <div class="form-group form-check">
        <input
          type="checkbox"
          :class="hasError('terms') ? 'is-invalid' : ''"
          class="form-check-input"
          v-model="formData.terms"
        />
        <label class="form-check-label"
          >I accept the
          <a href="/termsandconditions" target="_blank">
            terms and conditions
          </a></label
        >
        <div v-if="hasError('terms')" class="invalid-feedback">
          <div class="error" v-if="!$v.formData.terms.required">
            Please select terms and conditions.
          </div>
        </div>
      </div>
      
    </tab-content>
  </form-wizard>
</template>

`<script>
import { FormWizard, TabContent, ValidationHelper } from "vue-step-wizard";
import "vue-step-wizard/dist/vue-step-wizard.css";
import { required } from "vuelidate/lib/validators";
import { mapGetters, mapActions, mapState, mapMutations } from "vuex";
import CasteSelect from '../Layout/Components/CasteList';

const checked = (value) => value === true;


export default {
  name: "StepFormValidation",
  components: {
    FormWizard,
    TabContent,
    CasteSelect
  },
  mixins: [ValidationHelper],
  data() {
    return {
      /* formData: {
        name: '',

        subdomain: null,
        redirecturl: '',
        features: '',

        template_id: '',
        terms: false,
        reg_no: '',
        reg_act: '',
        reg_type: '',
       
        about: '',
        feature_name: ['membership', 'event'],
      },

      featuredata: [], */
      // submitted: false,
      validationRules: [
        { name: { required } },
        { subdomain: { required } },
       // { caste: { required }},
        {
          template_id: { required },
          terms: {
            checked,
          },
        },
      ],
      // submitted: false,
    };
  },
  created() {
    this.getFeatures();
  },
  computed: {
    ...mapGetters("website", ["featureList"]),
    ...mapGetters("user", ["loggedInUser"]),
    ...mapState("website", ["formData"]),
  },

  methods: {
    ...mapMutations("website", ["markSubmitted","setCaste"]),

    ...mapActions("website", ["createWebsite", "getFeatures"]),
    validateAndCreate() {
      this.markSubmitted();

      this.$v.$touch();
      if (!this.$v.$invalid) {
        this.createWebsite();
      }
    },
   reset() {
      for (let field in this.formData) {
        this.formData[field] = null;
      }
    },
  },
};
</script>`

`
<style scoped>
.v-application .error {
  background-color: #fff !important;
}
.cc-selector input {
  margin: 0;
  padding: 0;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
.visa {
  background-image: url("../assets/images/theme1.png");
}
.mastercard {
  background-image: url("../assets/images/theme2.jpg");
}

.cc-selector input:active + .drinkcard-cc {
  opacity: 0.9;
}
.cc-selector input:checked + .drinkcard-cc {
  -webkit-filter: none;
  -moz-filter: none;
  filter: none;
}
.top {
  margin-top: 20px;
}
.drinkcard-cc {
  cursor: pointer;
  background-size: contain;
  background-repeat: no-repeat;
  display: inline-block;
  width: 300px;
  height: 300px;
  -webkit-transition: all 100ms ease-in;
  -moz-transition: all 100ms ease-in;
  transition: all 100ms ease-in;
  -webkit-filter: brightness(1.8) grayscale(1) opacity(0.7);
  -moz-filter: brightness(1.8) grayscale(1) opacity(0.7);
  filter: brightness(1.8) grayscale(1) opacity(0.7);
}
.drinkcard-cc:hover {
  -webkit-filter: brightness(1.2) grayscale(0.5) opacity(0.9);
  -moz-filter: brightness(1.2) grayscale(0.5) opacity(0.9);
  filter: brightness(1.2) grayscale(0.5) opacity(0.9);
}

/* Extras */
a:visited {
  color: #888;
}
a {
  color: #444;
  text-decoration: none;
}
p {
  margin-bottom: 0.3em;
}
.card-header {
  margin-top: 5rem !important;
}
</style>`

**Comment by mathipa** [comment]
Hi @tushargugnani  how was this solved?
