### ISSUE TITLE
Validation on image

### ISSUE THREAD

**Issue by azermann** [tushargugnani/vue-step-wizard#3]
How do we validate images?

**Comment by tushargugnani** [comment]
@azermann Do you want to make image field required ?

**Comment by azermann** [comment]
@tushargugnani hi İ am using picture-input and yes i need a validate that new user put his image

**Comment by tushargugnani** [comment]
vue-step-wizard uses Vuelidate for Validations. You can write a custom validation that work on the @change event of the input. Example of custom image validation -> https://github.com/vuelidate/vuelidate/issues/429#issuecomment-540225850
