### ISSUE TITLE
Can't save it to fire base

### ISSUE THREAD

**Issue by azermann** [tushargugnani/vue-step-wizard#4]
Preflight response is not successful (error 1)
[Error] Fetch API  due to access control checks.
Failed to load resource: Preflight response is not successful
Unhandled Promise Rejection: Error: internal

search everywhere but none fix it on local or published to firebase how can we fix this and save data to firebase

**Comment by tushargugnani** [comment]
@azermann Where exactly you are getting this error?

**Comment by azermann** [comment]
@onclick event after I close alert

**Comment by tushargugnani** [comment]
The error you mentioned is related to the backend API where you are sending your data to.
This package deals with the frontend part of managing the multi-step form.

My advice would be try sending the data in required format to your API using a rest client (PostMan) and see if the API is working correctly. If yes, compare it debugging the data that you are sending on the submit event of the multi step form.
