### ISSUE TITLE
Next and Previous Step actions are not working

### ISSUE THREAD

**Issue by kaleidoscope-niraj** [tushargugnani/vue-step-wizard#6]
Can you implement @onNextStep="nextStep" @onPreviousStep="previousStep". I have tried to implement it but it's not working.

**Comment by tushargugnani** [comment]
@kaleidoscope-niraj Can you try to paste the implementation that you tried. 

You'll need to implement nextStep and the previousStep custom methods in your component where you are importing the FormWizard.

**Comment by tushargugnani** [comment]
@kaleidoscope-niraj Also, Make sure you are on the latest version of the plugin for this feature to work.

**Comment by kaleidoscope-niraj** [comment]
@tushargugnani I have tried to implement it as you have mentioned in the docs. But it is not working.
```
methods: {
    onComplete() {
      // debugger;
      this.saveBooking();
    },
     nextStep() {
      alert("Next Step");
    },
    previousStep() {
      alert("previous step");
    },
```

**Comment by tushargugnani** [comment]
@kaleidoscope-niraj Please update to the latest version for this functionality to work.

**Comment by kaleidoscope-niraj** [comment]
@tushargugnani Even the latest version is not working.

**Comment by tushargugnani** [comment]
Fixed
