### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content for .../js/vue-step-wizard.common.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by jekayode** [tushargugnani/vue-step-wizard#7]
Everything works perfectly but this error doesn't go away.

**Comment by tushargugnani** [comment]
@jekayode Can you put a screenshot of this error? Also can you try disabling Adblock or running the code into incognito mode to check if it still exists. Thanks

**Comment by jekayode** [comment]
Thank you for your swift response @tushargugnani 

This is in Google Chrome Incognito.

<img width="1269" alt="Screenshot 2020-08-10 at 11 17 44" src="https://user-images.githubusercontent.com/18671013/89773070-21fb8680-dafb-11ea-9413-2740dcc931df.png"> 

Regards

**Comment by tushargugnani** [comment]
Thank you, It's a warning. This should not effect the plugin functionality.  I will check and revert on the fix for this.

**Comment by jekayode** [comment]
Awesome. 

Yes, just as you've noted, everything works perfectly as expected. 

Thank you for the great job you are doing. 

I am learning from your blog and I hope very soon, I will be able to contribute to this and other Open Source projects from the knowlege.
